FROM python:3.8-slim-buster

RUN apt update
RUN apt install -y python3-dev gcc 

ADD requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

ADD main.py main.py

EXPOSE 8008

COPY . .

# Start the server
CMD ["python", "main.py", "development"]