version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8008:8008"
    volumes:
      - ./production:/production
    command: >
      python production/server.py &&
      python production/server.py dev
    restart: always
